<?php

namespace AppBundle\Repository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findActiveAds()
    {
        $em = $this->getEntityManager();        
        $query = $em->createQuery(
            'SELECT a FROM AppBundle:Ad a WHERE a.active = 1'
        );
        $ads = $query->getResult();
        
        return $ads;        
    }    
    
}
