<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Email AS email;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getAll()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT DISTINCT p.parentEmail 
            FROM AppBundle:Player p 
            WHERE p.parentEmail is not null
        ');
        $emails = $query->getScalarResult();       
        
        return $emails;        
    }

    public function getEmailAndYear()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT DISTINCT p.parentEmail, t.year 
            FROM AppBundle:Player p
            JOIN p.team t
            WHERE p.parentEmail is not null
        ');
        
        return $query->getScalarResult();              
    }    
    
    public function getByTeam()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT t.year FROM AppBundle:Team t WHERE t.isMy = 1
        ');
        
        return $query->getScalarResult();              
    }
    
    public function getEmailsByYear($year)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT DISTINCT p.parentEmail 
            FROM AppBundle:Player p
            JOIN AppBundle:Team t
            WITH p.team = t.id
            WHERE t.year = :year
        ')->setParameter('year', $year);
        $emails = $query->getScalarResult();       
        $array = array_column($emails, "parentEmail");
        $output = implode(", ", $array);
        
        return $output;
    }
    
}
