<?php

namespace AppBundle\Repository;

/**
 * PaymentCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
