<?php

namespace AppBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRandomPlayers()
    {               
        $em = $this->getEntityManager();
        $result = $em->createQuery("SELECT p.id FROM AppBundle:Player p")->getScalarResult();
        $ids = array_column($result, "id");        
        $randomIds = $this->randomIds($ids); 
        
        $query = $em->createQuery('
                SELECT p FROM AppBundle:Player p              
           WHERE p.id IN (:randomIds)
                ')->setParameter('randomIds', $randomIds);              
        $randomPlayers = $query->getResult();
        
        return $randomPlayers;
    }
    
    private function randomIds($ids) {
        shuffle($ids);
        if (sizeof($ids) < 4) {
            return array_slice($ids, 0, sizeof($ids));
        } else {
            return array_slice($ids, 0, 4);
        }
                
    }

    public function countPlayers()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT COUNT(p.id) FROM AppBundle:Player p');
        $count = $query->getSingleScalarResult(); 
        
        return $count;
    }
    
    
}
