<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRecentPosts()
    {               
        $em = $this->getEntityManager();        
        $query = $em->createQuery(
            'SELECT p FROM AppBundle:Post p ORDER BY p.publishDate'
            )->setMaxResults(5);
        $recentPosts = $query->getResult();
        
        return $recentPosts;
    } 
    
    public function countCategoryPosts($id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT COUNT(p.id)           
            FROM AppBundle:Post p
            JOIN p.categories c
            WHERE c.page = :id                
        ')->setParameter('id', $id);
        $count = $query->getSingleScalarResult(); 
        
        return $count;
    }    

    public function findCategoryPosts($id, $page, $perPage)
    {        
        $offset = 0; 

        if($page) {
            $page_value = $page;
            if($page_value > 1) {	
                $offset = ($page_value - 1) * $perPage;
            }
        }

        $em = $this->getEntityManager();        
        $query = $em->createQuery('
            SELECT p           
            FROM AppBundle:Post p
            JOIN p.categories c
            WHERE c.page = :id
        ')->setParameter('id', $id)->setMaxResults($perPage)->setFirstResult($offset);

        $news = $query->getResult();
        
        return $news;        
    }     
    
}
