<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRecentPosts()
    {               
        $em = $this->getEntityManager();        
        $query = $em->createQuery(
            'SELECT p FROM AppBundle:Post p ORDER BY p.publishDate'
            )->setMaxResults(5);
        $recentPosts = $query->getResult();
        
        return $recentPosts;
    } 
}
