<?php

namespace AppBundle\Repository;

/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestRepository extends \Doctrine\ORM\EntityRepository
{
//    public function searchByDate()
//    {               
//        $em = $this->getEntityManager();        
//        $query = $em->createQuery(
//            'SELECT r FROM AppBundle:Request r ORDER BY r.date DESC'
//        );
//        $fixtures = $query->getResult();
//        
//        return $fixtures;
//    }  
    
    public function getRecentRequests()
    {               
        $em = $this->getEntityManager();        
        $query = $em->createQuery(
            'SELECT r FROM AppBundle:Request r ORDER BY r.date DESC'
        )->setMaxResults(10);
        $fixtures = $query->getResult();
        
        return $fixtures;
    }    
    
}
