<?php

namespace AppBundle\Repository;

/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFirst()
    {
        $em = $this->getEntityManager();        
        $query = $em->createQuery(
            'SELECT s FROM AppBundle:Settings s ORDER BY s.id ASC'
        )->setMaxResults(1);
        $settings = $query->getSingleResult();
        
        return $settings;        
    }
}
