<?php

namespace AppBundle\Repository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function getYears() {
        $query = $this->getEntityManager()->createQuery(
                "SELECT DISTINCT t.year FROM AppBundle:Team t"
        )->getScalarResult();
        $years = array_column($query, "year");
        
        return $years;        
    }
}
