<?php

namespace AppBundle\Repository;

/**
 * TrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingRepository extends \Doctrine\ORM\EntityRepository
{   
    public function getTeamTrainings($year) {
        $query = $this->getEntityManager()->createQuery(
            "SELECT t 
             FROM AppBundle:Training t
             JOIN AppBundle:Team tm
             WITH t.team = tm.id
             WHERE tm.year = :year 
             ORDER BY t.day ASC"
        )->setParameter('year', $year);
        $trainings = $query->getResult();
        
        return $trainings;         
    }
}    
