<?php

namespace AppBundle\Repository;

/**
 * TrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingRepository extends \Doctrine\ORM\EntityRepository
{   
    public function getTeamTrainings($id) {
        $query = $this->getEntityManager()->createQuery(
            "SELECT t FROM AppBundle:Training t WHERE t.team = :id ORDER BY t.day ASC"
        )->setParameter('id', $id);
        $trainings = $query->getResult();
        
        return $trainings;         
    }
}    
