<?php

namespace AppBundle\Repository;

/**
 * TrainerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainerRepository extends \Doctrine\ORM\EntityRepository
{
}
