<?php

namespace AppBundle\Repository;

/**
 * User Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{   

    public function getUserPlayer($id)
    {
        $em = $this->getEntityManager();        
        $query = $em->createQuery(
            'SELECT IDENTITY(u.player) FROM AppBundle:User u WHERE u.id = :id'
        )->setParameter('id', $id);
        $games = $query->getSingleScalarResult();
        
        return $games;         
    }
    
}
