imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'    
        - 'SonataMediaBundle:Form:media_widgets.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:           
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true                 
                mappings:
                    ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
        
exercise_html_purifier:
    default:
        Cache.SerializerPath: '%kernel.cache_dir%/htmlpurifier'

sonata_admin:
    title: Sonata Admin Area
    templates:
        layout:                         ::standard_layout.html.twig
        ajax:                           ::ajax_layout.html.twig
        list:                           CRUD/list.html.twig
        show:                           CRUD/show.html.twig
        show_compare:                   CRUD/show_compare.html.twig
        edit:                           CRUD/edit.html.twig
        history:                        CRUD/history.html.twig
        preview:                        CRUD/preview.html.twig
        delete:                         CRUD/delete.html.twig
        batch:                          CRUD/list__batch.html.twig
        acl:                            CRUD/acl.html.twig
        action:                         CRUD/action.html.twig
        select:                         CRUD/list__select.html.twig
        filter:                         Form/filter_admin_fields.html.twig
        dashboard:                      Core/dashboard.html.twig
        search:                         Core/search.html.twig
        batch_confirmation:             CRUD/batch_confirmation.html.twig
        inner_list_row:                 CRUD/list_inner_row.html.twig
        base_list_field:                CRUD/base_list_field.html.twig
        list_block:                     Block/block_admin_list.html.twig
        user_block:                     Core/user_block.html.twig
        add_block:                      Core/add_block.html.twig
        pager_links:                    Pager/links.html.twig
        pager_results:                  Pager/results.html.twig
        tab_menu_template:              Core/tab_menu_template.html.twig
        history_revision_timestamp:     CRUD/history_revision_timestamp.html.twig
        short_object_description:       Helper/short-object-description.html.twig
        search_result_block:            Block/block_search_result.html.twig
        action_create:                  CRUD/dashboard__action_create.html.twig
        button_acl:                     Button/acl_button.html.twig
        button_create:                  Button/create_button.html.twig
        button_edit:                    Button/edit_button.html.twig
        button_history:                 Button/history_button.html.twig
        button_list:                    Button/list_button.html.twig
        button_show:                    Button/show_button.html.twig        
        
sonata_media:
    db_driver: doctrine_orm
    default_context: default
    contexts:
        default:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
                
        post:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo
            formats:
                small: { width: 150 , quality: 70}
                big:   { width: 400 , quality: 70}

        user:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 300 , quality: 70}

    cdn:
        server:
            path: /uploads/media

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false  

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]            
            
ivory_ck_editor:
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: admin_sonata_media_media_browser
            filebrowserImageBrowseRoute: admin_sonata_media_media_browser
            # Display images by default when clicking the image dialog browse button
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_sonata_media_media_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            # Upload file as image when sending a file from the image dialog
            filebrowserImageUploadRoute: admin_sonata_media_media_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: post            