app:
    resource: '@AppBundle/Controller/'
    type: annotation

service:
    resource: '@AppBundle/Service/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
artgris_bundle_file_manager:
    resource: "@ArtgrisFileManagerBundle/Controller"
    type:     annotation
    prefix:   /manager    
